spring:
  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  # Static resources reloading during development
  resources:
    static-locations: file:src/main/resources/static/
    cache-period: 0

  #URL jdbc de conexion con la BD
  datasource:
    url: jdbc:h2:./openwebinars
    username: sa
    password:

