spring:
  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  # Static resources reloading during development
  resources:
    static-locations: file:src/main/resources/static/
    cache-period: 0

  #URL jdbc de conexion con la BD
  datasource:
    url: jdbc:h2:./openwebinars
    #Usuario y contraseña de la BD
    username: sa
    password:

  #Habilitamos la consola de H2
  h2:
    console:
      enabled: true

  #Habilitamos los mensajes sql en el log
  jpa:
    show-sql: true